### ISSUE TITLE
Problem discussion

### ISSUE THREAD

**Issue by merwok** [nicain/reproduce_tox_issue#1]
The problem seems to be that your requirements are not complete, i.e. not produced by pip freeze or pip-compile.  In the first run, pip-sync installs pytest and its dependencies (py) implicitly; in the second run, py is removed because it’s not listed in the requirements file.

The correct flow is: write your direct dependencies in .in files (e.g. pytest in test-requirements.in), generate the list of all depencies with constraints resolved and exact versions (this will put pytest and py in test-requirements.txt).  pip-sync will then work as expected.

**Comment by nicain** [comment]
Something like described here?

http://jamescooke.info/a-successful-pip-tools-workflow-for-managing-python-package-requirements.html

**Comment by merwok** [comment]
Something like exactly what the pip-tools docs describe!  They edited the readme recently to make it even clearer than pip-sync needs frozen (complete) requirement files.

**Comment by nicain** [comment]
AWESOME! Pushed a complete fixed branch here: https://github.com/nicain/reproduce_tox_issue/tree/fix

@merwok thanks for all your help.  I am still learning all of this workflow, and I really appreciate you taking the time to educate me :)

**Comment by merwok** [comment]
Glad to help!  Happy solstice!

**Comment by merwok** [comment]
test requirements should not include (with -r) the base requirements.  See discussions in the open issues of pip-tools for more info.

**Comment by nicain** [comment]
OK.  I was following (my interpretation of) https://github.com/jazzband/pip-tools/issues/398#issuecomment-261313647

Is there a change in https://github.com/nicain/reproduce_tox_issue/tree/fix that I should make?

**Comment by merwok** [comment]
See these discussions:
 https://github.com/jazzband/pip-tools/pull/573#discussion_r152724221
 https://github.com/nedbat/django_coverage_plugin/issues/44

The change needed is: remove `-r requirements.txt` from test-requirements.in

**Comment by nicain** [comment]
Oh, I think I see; because of:

```
commands =
    pip-sync requirements.txt requirements-test.txt
    pyflakes project
    pytest {posargs}
```

Any runtime req's in requirements.in (converted to requirements.txt) are already taken care of.  This keeps requirements.txt (converted from requirements.in) clean, and only listing the testing dep's, right?

**Comment by merwok** [comment]
Exactly.
